### ISSUE TITLE
Can't press any buttons 

### ISSUE THREAD

**Issue by pixiandreas** [woutervanwijk/Mopidy-MusicBox-Webclient#105]
After 1 update mopidy to 1.0.5 and the new Webclient (2.0) all buttons exept "System" is working.
I follow the README in the directory

Info 
Ubuntu 14.04.02
mopidy is installed from (apt-mopidy)

When i pres a button on the gui i see that it changed in the address field:
http://127.0.0.1:6680/#browse

is it possible to start some debug ??

Andreas H

**Comment by kingosticks** [comment]
Have you cleared your Web cache?

**Comment by pixiandreas** [comment]
Yes i have empty this, i have try with 3 different browser and different OS

I have also install this setup on a raspberrypi , with exactly the same behavior

**Comment by pixiandreas** [comment]
Hello agin 

I reinstall everything again and now it works, sorry for this

**Comment by kingosticks** [comment]
Strange, but thanks for updating this issue.

**Comment by maemigh** [comment]
I'm having this issue as well. There appear to be some javascript errors after I upgrade to webclient 2.0.0 (and I'm assuming these are causing the issue).

index.html line 16: Uncaught SyntaxError: Unexpected token {

16: var isMusicBox = {{musicbox}}; // Remove MusicBox only content (e.g. settings, system pages)

gui.js:460 Uncaught ReferenceError: wsLocation is not defined

460:  webSocketUrl: 'ws://' + wsLocation + '/mopidy/ws/' // wslocation is set in index.html "ws://localhost:6680/mopidy/ws/"

**Comment by kingosticks** [comment]
Ahh, thanks for the extra detail, I know what this is now.

In version 2.0.0 we changed from a static client to a webapp and so you must remove your `static_dir` config setting. Instances of `{{foo}}` are templating placeholders that the server side portion of the app substitutes actual values for. `static_dir` tells Mopidy to just serve the html "as it" and so these substitutions don't occur and the syntax left behind isn't valid javascript.

If you still want http://localhost:6680 to show musicbox-webclient (rather than Mopidy's default list of installed clients) you can set up a reverse proxy, or, point `static_dir` to a redirection-only page as mentioned [here](https://github.com/woutervanwijk/Pi-MusicBox/wiki/Updating-components-to-latest-versions#4-fix-ups-after-python-packages-update). 

For example, set `static_dir = /var/lib/mopidy/redirect.html` and save the following in /var/lib/mopidy/redirect.html :
```
<html>
<head><meta http-equiv="refresh" content="0; URL=/musicbox_webclient"></head>
<body><a href="/musicbox_webclient">musicbox_webclient</a></body>
</html>
```

**Comment by kingosticks** [comment]
I've realised it's actually pretty simple to make the client support `static_dir` configurations for those that are happy with the default options. But if you do want to enable the musicbox/alarmclock integration or set a non-standard websocket URL then that's only possible in "webapp mode".

**Comment by DavisNT** [comment]
I think that users might get different behavior of Musicbox Webclient when used with different URLs (i.e. `/` vs `/musicbox_webclient/`).
I would like to propose creating a redirection to `/musicbox_webclient/` when Musicbox Webclient is opened in `/` (by using `static_dir`). @kingosticks what do you think by this idea? Can I make a Pull Request for it?

**Comment by kingosticks** [comment]
I should have fixed the problem in the latest code. There shouldn't be any
more issues relating to this.

**Comment by DavisNT** [comment]
Probably you didn't get my idea.
Current implementation (latest code in `develop` branch) does **not** show Alarm Clock link and does **not** read custom config if opened as http://musicbox.local (using `static_dir`), but it shows Alarm Clock (if present) and reads custom config if opened as http://musicbox.local/musicbox_webclient/

I propose a redirect to `/musicbox_webclient/` when opening the webapp using `static_dir`.
Technically this could be achieved by placing a redirect in `index.html` file and renaming real `index.html` (to let's say `index.template`) and changing `IndexHandler` in `web.py` to parse new filename (e.g. `index.template`) instread of `index.html`.

What do you think about this?

**Comment by kingosticks** [comment]
Oh I see now. But as far as I'm concerned If people want the new
functionality they need to use in as a Webapp and sort out any
redirection/URL prettifying externally. What I added was just to support
backwards compatibility.

**Comment by DavisNT** [comment]
Okie, can I create the redirection inside Musicbox Webclient for backwards compatibility while maintaining full webapp functionality with existing webapp URLs (i.e. can I make a Pull Request)?

**Comment by kingosticks** [comment]
I really don't see the point of having any sort of redirection in the
webclient. It's added complication for a problem far better solved outside
of this project.

**Comment by DavisNT** [comment]
I don't see any technical complications with redirection. Though it will remove hardcoded default config form `index.html` and actually reduce complexity of Webclient (because now we really have 2 cases to test/maintain - Webclient used as webapp and as static page).

If Pi MusicBox does not have a redirection by default, then **most** users will not ever see the advantages of webapp (e.g. Alarm Clock link).

The only con I see for redirection is a delay while browser is being redirected. An alternative would be having a separate dynamically generated JavaScript file which would be referenced in `index.html` by host relative URL (e.g. `/musicbox_webclient/settings.js`). Then any transformations of `index.html` could be removed and configuration would always be read using the new JavaScript file from the webapp. In this case Musicbox Webclient would be fully functional when opened as webapp or static page (because in both cases it would get config from dynamicly generated JavaScript file in webapp). What do you think about this proposal?

**Comment by kingosticks** [comment]
Pi musicbox isn't relevant here, everything* will work as expected in the
next releases with working links to alarm clock and whatever. The solution
needs to be outside of the Webclient since it has to work for all the
clients, not just musicbox-webclient.

**Comment by puyamn** [comment]
I have the same problem since I updated the webclient this morning. The updated version works over http://musicbox.local/musicbox_webclient/index.html and I can get the redirection working, but I can't see any music, neither from spotify nor from my nas.
