### ISSUE TITLE
internet remore acess

### ISSUE THREAD

**Issue by Luis-Lourenco** [woutervanwijk/Mopidy-MusicBox-Webclient#273]
Hi, I'm Luis from Portugal I'm just starting my pimusicbox.

Everything I can add, also mp3 and web radios.

But for my colleagues also can manage the radio, I setup a internet remote access on a public link on my server over https.

The problem is when I type the link, the menu opens ok, but always get the message on the middle screen:
REMOVED

Where I can find the web server configuration file to add my public link?

kind regards,
Luis Lourenço

**Comment by kingosticks** [comment]
Hi,
I've removed the image as it contains your IP address and there's no need to make this idea any less secure by including that information. That "Trying to reach Musicbox" message means the websocket connection cannot be made. 

Is this PiMusicbox or is this Mopidy 3 you are running? I don't recommend exposing either on the public internet but PiMusicbox even less so. 

The config for this extension (Mopidy-Musicbox-Webclient) is documented in the README, it includes a `websocket_host` and `websocket_port` which needs to point to your Mopidy server but that depends on your setup and I can't help you get that right. Hopefully, since you are even considering doing this, you know what you are doing and these config settings make sense to you. 

Mopidy's general HTTP config is documented at https://docs.mopidy.com/en/latest/ext/http/ but I don't think that is your problem here.

**Comment by kingosticks** [comment]
No response, closing.
