### ISSUE TITLE
Settings menu item still showing on a non Pi MusicBox installation

### ISSUE THREAD

**Issue by DietShasta** [woutervanwijk/Mopidy-MusicBox-Webclient#55]
Hello, I know this issue was originally closed, but I still seem to be showing the "Settings" link despite upgrading to the newest version using the pip upgrade just now. Is there any other step I could be missing?

**Comment by nixpanic** [comment]
I hit this issue too, when clicking on "settings", I get a page that says:

    404: Not Found

**Comment by kingosticks** [comment]
I'd forgotten about this one, thanks for the reminder and will look to get it fixed in the next couple of days. If you wanted to edit the html file to remove the links it'd be line 16 in /usr/local/lib/python2.7/dist-packages/mopidy_musicbox_webclient/static/index.html (or wherever the installed files live on your system).

**Comment by kingosticks** [comment]
Fixed in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/0bd7eff8d60595c9ad8d62afbe88668a05758d12

There's a `musicbox` config option which controls if these navigation links are shown, it defaults to false.
